site_name: Aneka Cloud Application Platform
site_url: https://github.com/shivupoojar/AnekaPrograms
theme:
  name: material
  logo: assets/manjrasoftlogo.png
  palette:
    primary: white
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit
    - content.action.view
    - navigation.footer

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/shivupoojar/AnekaPrograms
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/manjrasoft-pty-ltd/about/

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.pathconverter:
      base_path: '' # default: ''
      relative_path: '' # default ''
      absolute: false # default: false
      tags: 'a script img link object embed'
      
copyright: |
  &copy; 2023 <a href="http://manjrasoft.com"  target="_blank" rel="noopener">Manjrasoft Pty Ltd</a>
