site_name: Aneka Cloud Application Platform
theme:
  name: material
  logo: assets/manjrasoftlogo.png
  palette:
    primary: white
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit
    - content.action.view
    - navigation.footer
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji

copyright: |
  &copy; 2023 <a href="http://manjrasoft.com"  target="_blank" rel="noopener">Manjrasoft Pty Ltd</a>
